
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package power.keepeersofthestones.init;

import power.keepeersofthestones.item.WoodenShieldItem;
import power.keepeersofthestones.item.WindItem;
import power.keepeersofthestones.item.WhirlpoolItem;
import power.keepeersofthestones.item.WaterStoneItem;
import power.keepeersofthestones.item.WaterKatanaItem;
import power.keepeersofthestones.item.WaterItem;
import power.keepeersofthestones.item.WaterFlowItem;
import power.keepeersofthestones.item.WaterDropItem;
import power.keepeersofthestones.item.WaterBatteryItem;
import power.keepeersofthestones.item.VampirismItem;
import power.keepeersofthestones.item.VacuumWebItem;
import power.keepeersofthestones.item.VacuumSwordItem;
import power.keepeersofthestones.item.VacuumStoneItem;
import power.keepeersofthestones.item.VacuumSpiralItem;
import power.keepeersofthestones.item.VacuumItem;
import power.keepeersofthestones.item.VacuumBatteryItem;
import power.keepeersofthestones.item.TpOnVenusItem;
import power.keepeersofthestones.item.TpOnMoonItem;
import power.keepeersofthestones.item.TpOnMarsItem;
import power.keepeersofthestones.item.TpOnEarthItem;
import power.keepeersofthestones.item.TornadoStoneItem;
import power.keepeersofthestones.item.TornadoItem;
import power.keepeersofthestones.item.TornadoCreateItem;
import power.keepeersofthestones.item.TornadoBattleAxeItem;
import power.keepeersofthestones.item.TornadoBatteryItem;
import power.keepeersofthestones.item.TimeStopItem;
import power.keepeersofthestones.item.TimeStoneItem;
import power.keepeersofthestones.item.TimeReversedItem;
import power.keepeersofthestones.item.TimeItem;
import power.keepeersofthestones.item.TimeDilationItem;
import power.keepeersofthestones.item.TimeBladeItem;
import power.keepeersofthestones.item.TimeBatteryItem;
import power.keepeersofthestones.item.TigerClawItem;
import power.keepeersofthestones.item.TeleportationStoneItem;
import power.keepeersofthestones.item.TeleportationItem;
import power.keepeersofthestones.item.TeleportationBatteryItem;
import power.keepeersofthestones.item.TechnologyStoneItem;
import power.keepeersofthestones.item.TechnologyItem;
import power.keepeersofthestones.item.TechnologyBatteryItem;
import power.keepeersofthestones.item.TechnobarrierItem;
import power.keepeersofthestones.item.TechnoPickaxeItem;
import power.keepeersofthestones.item.TamerItem;
import power.keepeersofthestones.item.SunStoneItem;
import power.keepeersofthestones.item.SunRegenerationItem;
import power.keepeersofthestones.item.SunRayItem;
import power.keepeersofthestones.item.SunItem;
import power.keepeersofthestones.item.SunExplodeItem;
import power.keepeersofthestones.item.SunBatteryItem;
import power.keepeersofthestones.item.SunAxeItem;
import power.keepeersofthestones.item.StormItem;
import power.keepeersofthestones.item.SpiritStoneItem;
import power.keepeersofthestones.item.SpikeItem;
import power.keepeersofthestones.item.SpeedStoneItem;
import power.keepeersofthestones.item.SpawnItem;
import power.keepeersofthestones.item.SoundSwordItem;
import power.keepeersofthestones.item.SoundStoneItem;
import power.keepeersofthestones.item.SoundItem;
import power.keepeersofthestones.item.SoundEmitateItem;
import power.keepeersofthestones.item.SoundBatteryItem;
import power.keepeersofthestones.item.SoundBarrierItem;
import power.keepeersofthestones.item.SnowGolemCreatorItem;
import power.keepeersofthestones.item.SmokeStoneItem;
import power.keepeersofthestones.item.ShurikenItem;
import power.keepeersofthestones.item.ShieldOfEarthItem;
import power.keepeersofthestones.item.ShadowarmorItem;
import power.keepeersofthestones.item.ShadowSwordItem;
import power.keepeersofthestones.item.ShadowStoneItem;
import power.keepeersofthestones.item.ShadowInvisibleItem;
import power.keepeersofthestones.item.ShadowBatteryItem;
import power.keepeersofthestones.item.ShadowBallItem;
import power.keepeersofthestones.item.SandStoneItem;
import power.keepeersofthestones.item.SaiItem;
import power.keepeersofthestones.item.RoseSwordItem;
import power.keepeersofthestones.item.RedstoneBundleItem;
import power.keepeersofthestones.item.RandomItemItem;
import power.keepeersofthestones.item.RainfallItem;
import power.keepeersofthestones.item.RainStoneItem;
import power.keepeersofthestones.item.RainKnifeItem;
import power.keepeersofthestones.item.RainItem;
import power.keepeersofthestones.item.RainBowItem;
import power.keepeersofthestones.item.RainBatteryItem;
import power.keepeersofthestones.item.PortalBlastItem;
import power.keepeersofthestones.item.PoisonStoneItem;
import power.keepeersofthestones.item.PlasmaBallItem;
import power.keepeersofthestones.item.PlagueStoneItem;
import power.keepeersofthestones.item.PieceOfEarthItem;
import power.keepeersofthestones.item.OceanSwordItem;
import power.keepeersofthestones.item.OceanStoneItem;
import power.keepeersofthestones.item.OceanItem;
import power.keepeersofthestones.item.OceanBatteryItem;
import power.keepeersofthestones.item.MushroomsStoneItem;
import power.keepeersofthestones.item.MoonWitherItem;
import power.keepeersofthestones.item.MoonStonesItem;
import power.keepeersofthestones.item.MoonStoneItem;
import power.keepeersofthestones.item.MoonBatteryItem;
import power.keepeersofthestones.item.MoonAxeItem;
import power.keepeersofthestones.item.MistStoneItem;
import power.keepeersofthestones.item.MetalStoneItem;
import power.keepeersofthestones.item.MetalItem;
import power.keepeersofthestones.item.MetalInvulnerabilityItem;
import power.keepeersofthestones.item.MetalBatteryItem;
import power.keepeersofthestones.item.MegawattItem;
import power.keepeersofthestones.item.MagmaShieldItem;
import power.keepeersofthestones.item.MagicFireballItem;
import power.keepeersofthestones.item.MaceItem;
import power.keepeersofthestones.item.LightningStrikeItem;
import power.keepeersofthestones.item.LightningStoneItem;
import power.keepeersofthestones.item.LightningItem;
import power.keepeersofthestones.item.LightningBatteryItem;
import power.keepeersofthestones.item.LightingItem;
import power.keepeersofthestones.item.LightSwordItem;
import power.keepeersofthestones.item.LightStoneItem;
import power.keepeersofthestones.item.LightItem;
import power.keepeersofthestones.item.LightBatteryItem;
import power.keepeersofthestones.item.LavaStoneItem;
import power.keepeersofthestones.item.LavaItem;
import power.keepeersofthestones.item.LavaHoleItem;
import power.keepeersofthestones.item.LavaHammerItem;
import power.keepeersofthestones.item.LavaBatteryItem;
import power.keepeersofthestones.item.LavaBallItem;
import power.keepeersofthestones.item.IronShieldItem;
import power.keepeersofthestones.item.IronGolemCreateItem;
import power.keepeersofthestones.item.IncreasePowerItem;
import power.keepeersofthestones.item.IceStoneItem;
import power.keepeersofthestones.item.IceSpearItem;
import power.keepeersofthestones.item.IceShieldItem;
import power.keepeersofthestones.item.IceSharpItem;
import power.keepeersofthestones.item.IceItem;
import power.keepeersofthestones.item.IceBatteryItem;
import power.keepeersofthestones.item.IceBallItem;
import power.keepeersofthestones.item.GreeneryStoneItem;
import power.keepeersofthestones.item.GreeneryItem;
import power.keepeersofthestones.item.GreeneryBatteryItem;
import power.keepeersofthestones.item.GravityStoneItem;
import power.keepeersofthestones.item.GoldenCrossbowItem;
import power.keepeersofthestones.item.GlowCreateItem;
import power.keepeersofthestones.item.GalacticSwordItem;
import power.keepeersofthestones.item.ForcereplicationItem;
import power.keepeersofthestones.item.FlashLightItem;
import power.keepeersofthestones.item.FistofEarthItem;
import power.keepeersofthestones.item.FireSwordItem;
import power.keepeersofthestones.item.FireStoneItem;
import power.keepeersofthestones.item.FireItem;
import power.keepeersofthestones.item.FireBatteryItem;
import power.keepeersofthestones.item.FertilizerItem;
import power.keepeersofthestones.item.ExplosiveFlowItem;
import power.keepeersofthestones.item.ExplosionStoneItem;
import power.keepeersofthestones.item.ExplosionBatteryItem;
import power.keepeersofthestones.item.ExplodeItem;
import power.keepeersofthestones.item.EnergyStoneItem;
import power.keepeersofthestones.item.EnergyStaffItem;
import power.keepeersofthestones.item.EnergySphereItem;
import power.keepeersofthestones.item.EnergyShieldItem;
import power.keepeersofthestones.item.EnergyItem;
import power.keepeersofthestones.item.EnergyBatteryItem;
import power.keepeersofthestones.item.EnergyAbsorptionItem;
import power.keepeersofthestones.item.EmptyBatteryItem;
import power.keepeersofthestones.item.ElementalMusicDiscItem;
import power.keepeersofthestones.item.EclipseItem;
import power.keepeersofthestones.item.EarthStoneItem;
import power.keepeersofthestones.item.EarthItem;
import power.keepeersofthestones.item.EarthBatteryItem;
import power.keepeersofthestones.item.DestructionStoneItem;
import power.keepeersofthestones.item.DestructionSphereItem;
import power.keepeersofthestones.item.DestructionPowerItem;
import power.keepeersofthestones.item.DestructionItem;
import power.keepeersofthestones.item.CutterSwordItem;
import power.keepeersofthestones.item.CultivationItem;
import power.keepeersofthestones.item.CrystalStoneItem;
import power.keepeersofthestones.item.CrystalShieldItem;
import power.keepeersofthestones.item.CrystalItem;
import power.keepeersofthestones.item.CrystalDaggerItem;
import power.keepeersofthestones.item.CrystalBatteryItem;
import power.keepeersofthestones.item.CrestcentItem;
import power.keepeersofthestones.item.CreationStoneItem;
import power.keepeersofthestones.item.CreationItem;
import power.keepeersofthestones.item.CreateShadowItem;
import power.keepeersofthestones.item.CosmosStoneItem;
import power.keepeersofthestones.item.CosmosItem;
import power.keepeersofthestones.item.CosmosBatteryItem;
import power.keepeersofthestones.item.CoralShieldItem;
import power.keepeersofthestones.item.ConstructionsItem;
import power.keepeersofthestones.item.ClusterSharpItem;
import power.keepeersofthestones.item.CheckpointItem;
import power.keepeersofthestones.item.BurnItem;
import power.keepeersofthestones.item.BookOfElementsItem;
import power.keepeersofthestones.item.BoStaffItem;
import power.keepeersofthestones.item.BlueKnifeItem;
import power.keepeersofthestones.item.BlueFlameStoneItem;
import power.keepeersofthestones.item.BloodStoneItem;
import power.keepeersofthestones.item.BloodReaperItem;
import power.keepeersofthestones.item.BloodItem;
import power.keepeersofthestones.item.BloodBatteryItem;
import power.keepeersofthestones.item.BlackHoleItem;
import power.keepeersofthestones.item.BlackHeartItem;
import power.keepeersofthestones.item.BeeStingItem;
import power.keepeersofthestones.item.AnimalsStoneItem;
import power.keepeersofthestones.item.AnimalsItem;
import power.keepeersofthestones.item.AnimalsBatteryItem;
import power.keepeersofthestones.item.AmberStoneItem;
import power.keepeersofthestones.item.AmberItem;
import power.keepeersofthestones.item.AirStoneItem;
import power.keepeersofthestones.item.AirFlowItem;
import power.keepeersofthestones.item.AirBladeItem;
import power.keepeersofthestones.item.AirBatteryItem;
import power.keepeersofthestones.item.AcusticalExplodeItem;
import power.keepeersofthestones.item.AccelerationTimeItem;
import power.keepeersofthestones.PowerMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

public class PowerModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, PowerMod.MODID);
	public static final RegistryObject<Item> FIRE_STONE = REGISTRY.register("fire_stone", () -> new FireStoneItem());
	public static final RegistryObject<Item> AIR_STONE = REGISTRY.register("air_stone", () -> new AirStoneItem());
	public static final RegistryObject<Item> WATER_STONE = REGISTRY.register("water_stone", () -> new WaterStoneItem());
	public static final RegistryObject<Item> EARTH_STONE = REGISTRY.register("earth_stone", () -> new EarthStoneItem());
	public static final RegistryObject<Item> GREENERY_STONE = REGISTRY.register("greenery_stone", () -> new GreeneryStoneItem());
	public static final RegistryObject<Item> ANIMALS_STONE = REGISTRY.register("animals_stone", () -> new AnimalsStoneItem());
	public static final RegistryObject<Item> TECHNOLOGY_STONE = REGISTRY.register("technology_stone", () -> new TechnologyStoneItem());
	public static final RegistryObject<Item> METAL_STONE = REGISTRY.register("metal_stone", () -> new MetalStoneItem());
	public static final RegistryObject<Item> LIGHT_STONE = REGISTRY.register("light_stone", () -> new LightStoneItem());
	public static final RegistryObject<Item> SHADOW_STONE = REGISTRY.register("shadow_stone", () -> new ShadowStoneItem());
	public static final RegistryObject<Item> ENERGY_STONE = REGISTRY.register("energy_stone", () -> new EnergyStoneItem());
	public static final RegistryObject<Item> SPIRIT_STONE = REGISTRY.register("spirit_stone", () -> new SpiritStoneItem());
	public static final RegistryObject<Item> VACUUM_STONE = REGISTRY.register("vacuum_stone", () -> new VacuumStoneItem());
	public static final RegistryObject<Item> ICE_STONE = REGISTRY.register("ice_stone", () -> new IceStoneItem());
	public static final RegistryObject<Item> LIGHTNING_STONE = REGISTRY.register("lightning_stone", () -> new LightningStoneItem());
	public static final RegistryObject<Item> SOUND_STONE = REGISTRY.register("sound_stone", () -> new SoundStoneItem());
	public static final RegistryObject<Item> CRYSTAL_STONE = REGISTRY.register("crystal_stone", () -> new CrystalStoneItem());
	public static final RegistryObject<Item> LAVA_STONE = REGISTRY.register("lava_stone", () -> new LavaStoneItem());
	public static final RegistryObject<Item> RAIN_STONE = REGISTRY.register("rain_stone", () -> new RainStoneItem());
	public static final RegistryObject<Item> TORNADO_STONE = REGISTRY.register("tornado_stone", () -> new TornadoStoneItem());
	public static final RegistryObject<Item> OCEAN_STONE = REGISTRY.register("ocean_stone", () -> new OceanStoneItem());
	public static final RegistryObject<Item> BLOOD_STONE = REGISTRY.register("blood_stone", () -> new BloodStoneItem());
	public static final RegistryObject<Item> TELEPORTATION_STONE = REGISTRY.register("teleportation_stone", () -> new TeleportationStoneItem());
	public static final RegistryObject<Item> EXPLOSION_STONE = REGISTRY.register("explosion_stone", () -> new ExplosionStoneItem());
	public static final RegistryObject<Item> AMBER_STONE = REGISTRY.register("amber_stone", () -> new AmberStoneItem());
	public static final RegistryObject<Item> BLUE_FLAME_STONE = REGISTRY.register("blue_flame_stone", () -> new BlueFlameStoneItem());
	public static final RegistryObject<Item> MIST_STONE = REGISTRY.register("mist_stone", () -> new MistStoneItem());
	public static final RegistryObject<Item> SMOKE_STONE = REGISTRY.register("smoke_stone", () -> new SmokeStoneItem());
	public static final RegistryObject<Item> POISON_STONE = REGISTRY.register("poison_stone", () -> new PoisonStoneItem());
	public static final RegistryObject<Item> PLAGUE_STONE = REGISTRY.register("plague_stone", () -> new PlagueStoneItem());
	public static final RegistryObject<Item> GRAVITY_STONE = REGISTRY.register("gravity_stone", () -> new GravityStoneItem());
	public static final RegistryObject<Item> SPEED_STONE = REGISTRY.register("speed_stone", () -> new SpeedStoneItem());
	public static final RegistryObject<Item> SAND_STONE = REGISTRY.register("sand_stone", () -> new SandStoneItem());
	public static final RegistryObject<Item> SUN_STONE = REGISTRY.register("sun_stone", () -> new SunStoneItem());
	public static final RegistryObject<Item> MOON_STONE = REGISTRY.register("moon_stone", () -> new MoonStoneItem());
	public static final RegistryObject<Item> COSMOS_STONE = REGISTRY.register("cosmos_stone", () -> new CosmosStoneItem());
	public static final RegistryObject<Item> TIME_STONE = REGISTRY.register("time_stone", () -> new TimeStoneItem());
	public static final RegistryObject<Item> CREATION_STONE = REGISTRY.register("creation_stone", () -> new CreationStoneItem());
	public static final RegistryObject<Item> DESTRUCTION_STONE = REGISTRY.register("destruction_stone", () -> new DestructionStoneItem());
	public static final RegistryObject<Item> MACE = REGISTRY.register("mace", () -> new MaceItem());
	public static final RegistryObject<Item> FORCE_REPLICATION = REGISTRY.register("force_replication", () -> new ForcereplicationItem());
	public static final RegistryObject<Item> CUTTER_SWORD = REGISTRY.register("cutter_sword", () -> new CutterSwordItem());
	public static final RegistryObject<Item> ELEMENTAL_MUSIC_DISC = REGISTRY.register("elemental_music_disc", () -> new ElementalMusicDiscItem());
	public static final RegistryObject<Item> EMPTY_BATTERY = REGISTRY.register("empty_battery", () -> new EmptyBatteryItem());
	public static final RegistryObject<Item> FIRE_BATTERY = REGISTRY.register("fire_battery", () -> new FireBatteryItem());
	public static final RegistryObject<Item> AIR_BATTERY = REGISTRY.register("air_battery", () -> new AirBatteryItem());
	public static final RegistryObject<Item> WATER_BATTERY = REGISTRY.register("water_battery", () -> new WaterBatteryItem());
	public static final RegistryObject<Item> EARTH_BATTERY = REGISTRY.register("earth_battery", () -> new EarthBatteryItem());
	public static final RegistryObject<Item> ENERGY_BATTERY = REGISTRY.register("energy_battery", () -> new EnergyBatteryItem());
	public static final RegistryObject<Item> ICE_BATTERY = REGISTRY.register("ice_battery", () -> new IceBatteryItem());
	public static final RegistryObject<Item> LIGHTNING_BATTERY = REGISTRY.register("lightning_battery", () -> new LightningBatteryItem());
	public static final RegistryObject<Item> SOUND_BATTERY = REGISTRY.register("sound_battery", () -> new SoundBatteryItem());
	public static final RegistryObject<Item> CRYSTAL_BATTERY = REGISTRY.register("crystal_battery", () -> new CrystalBatteryItem());
	public static final RegistryObject<Item> LAVA_BATTERY = REGISTRY.register("lava_battery", () -> new LavaBatteryItem());
	public static final RegistryObject<Item> RAIN_BATTERY = REGISTRY.register("rain_battery", () -> new RainBatteryItem());
	public static final RegistryObject<Item> TORNADO_BATTERY = REGISTRY.register("tornado_battery", () -> new TornadoBatteryItem());
	public static final RegistryObject<Item> OCEAN_BATTERY = REGISTRY.register("ocean_battery", () -> new OceanBatteryItem());
	public static final RegistryObject<Item> GREENERY_BATTERY = REGISTRY.register("greenery_battery", () -> new GreeneryBatteryItem());
	public static final RegistryObject<Item> ANIMALS_BATTERY = REGISTRY.register("animals_battery", () -> new AnimalsBatteryItem());
	public static final RegistryObject<Item> METAL_BATTERY = REGISTRY.register("metal_battery", () -> new MetalBatteryItem());
	public static final RegistryObject<Item> LIGHT_BATTERY = REGISTRY.register("light_battery", () -> new LightBatteryItem());
	public static final RegistryObject<Item> SHADOW_BATTERY = REGISTRY.register("shadow_battery", () -> new ShadowBatteryItem());
	public static final RegistryObject<Item> VACUUM_BATTERY = REGISTRY.register("vacuum_battery", () -> new VacuumBatteryItem());
	public static final RegistryObject<Item> SUN_BATTERY = REGISTRY.register("sun_battery", () -> new SunBatteryItem());
	public static final RegistryObject<Item> MOON_BATTERY = REGISTRY.register("moon_battery", () -> new MoonBatteryItem());
	public static final RegistryObject<Item> COSMOS_BATTERY = REGISTRY.register("cosmos_battery", () -> new CosmosBatteryItem());
	public static final RegistryObject<Item> BLOOD_BATTERY = REGISTRY.register("blood_battery", () -> new BloodBatteryItem());
	public static final RegistryObject<Item> TIME_BATTERY = REGISTRY.register("time_battery", () -> new TimeBatteryItem());
	public static final RegistryObject<Item> TECHNOLOGY_BATTERY = REGISTRY.register("technology_battery", () -> new TechnologyBatteryItem());
	public static final RegistryObject<Item> TELEPORTATION_BATTERY = REGISTRY.register("teleportation_battery", () -> new TeleportationBatteryItem());
	public static final RegistryObject<Item> EXPLOSION_BATTERY = REGISTRY.register("explosion_battery", () -> new ExplosionBatteryItem());
	public static final RegistryObject<Item> BATTERY_CHARGER = block(PowerModBlocks.BATTERY_CHARGER, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BURN = REGISTRY.register("burn", () -> new BurnItem());
	public static final RegistryObject<Item> MAGIC_FIREBALL = REGISTRY.register("magic_fireball", () -> new MagicFireballItem());
	public static final RegistryObject<Item> AIR_FLOW = REGISTRY.register("air_flow", () -> new AirFlowItem());
	public static final RegistryObject<Item> WATER_FLOW = REGISTRY.register("water_flow", () -> new WaterFlowItem());
	public static final RegistryObject<Item> WATER_DROP = REGISTRY.register("water_drop", () -> new WaterDropItem());
	public static final RegistryObject<Item> FIRE_HELMET = REGISTRY.register("fire_helmet", () -> new FireItem.Helmet());
	public static final RegistryObject<Item> FIRE_CHESTPLATE = REGISTRY.register("fire_chestplate", () -> new FireItem.Chestplate());
	public static final RegistryObject<Item> FIRE_LEGGINGS = REGISTRY.register("fire_leggings", () -> new FireItem.Leggings());
	public static final RegistryObject<Item> FIRE_BOOTS = REGISTRY.register("fire_boots", () -> new FireItem.Boots());
	public static final RegistryObject<Item> WATER_HELMET = REGISTRY.register("water_helmet", () -> new WaterItem.Helmet());
	public static final RegistryObject<Item> WATER_CHESTPLATE = REGISTRY.register("water_chestplate", () -> new WaterItem.Chestplate());
	public static final RegistryObject<Item> WATER_LEGGINGS = REGISTRY.register("water_leggings", () -> new WaterItem.Leggings());
	public static final RegistryObject<Item> WATER_BOOTS = REGISTRY.register("water_boots", () -> new WaterItem.Boots());
	public static final RegistryObject<Item> FISTOF_EARTH = REGISTRY.register("fistof_earth", () -> new FistofEarthItem());
	public static final RegistryObject<Item> SHIELD_OF_EARTH = REGISTRY.register("shield_of_earth", () -> new ShieldOfEarthItem());
	public static final RegistryObject<Item> WIND_HELMET = REGISTRY.register("wind_helmet", () -> new WindItem.Helmet());
	public static final RegistryObject<Item> WIND_CHESTPLATE = REGISTRY.register("wind_chestplate", () -> new WindItem.Chestplate());
	public static final RegistryObject<Item> WIND_LEGGINGS = REGISTRY.register("wind_leggings", () -> new WindItem.Leggings());
	public static final RegistryObject<Item> WIND_BOOTS = REGISTRY.register("wind_boots", () -> new WindItem.Boots());
	public static final RegistryObject<Item> PIECE_OF_EARTH = REGISTRY.register("piece_of_earth", () -> new PieceOfEarthItem());
	public static final RegistryObject<Item> EARTH_HELMET = REGISTRY.register("earth_helmet", () -> new EarthItem.Helmet());
	public static final RegistryObject<Item> EARTH_CHESTPLATE = REGISTRY.register("earth_chestplate", () -> new EarthItem.Chestplate());
	public static final RegistryObject<Item> EARTH_LEGGINGS = REGISTRY.register("earth_leggings", () -> new EarthItem.Leggings());
	public static final RegistryObject<Item> EARTH_BOOTS = REGISTRY.register("earth_boots", () -> new EarthItem.Boots());
	public static final RegistryObject<Item> ENERGY_HELMET = REGISTRY.register("energy_helmet", () -> new EnergyItem.Helmet());
	public static final RegistryObject<Item> ENERGY_CHESTPLATE = REGISTRY.register("energy_chestplate", () -> new EnergyItem.Chestplate());
	public static final RegistryObject<Item> ENERGY_LEGGINGS = REGISTRY.register("energy_leggings", () -> new EnergyItem.Leggings());
	public static final RegistryObject<Item> ENERGY_BOOTS = REGISTRY.register("energy_boots", () -> new EnergyItem.Boots());
	public static final RegistryObject<Item> ENERGY_SPHERE = REGISTRY.register("energy_sphere", () -> new EnergySphereItem());
	public static final RegistryObject<Item> ENERGY_BLOCK = block(PowerModBlocks.ENERGY_BLOCK, null);
	public static final RegistryObject<Item> ENERGY_SHIELD = REGISTRY.register("energy_shield", () -> new EnergyShieldItem());
	public static final RegistryObject<Item> ICE_BALL = REGISTRY.register("ice_ball", () -> new IceBallItem());
	public static final RegistryObject<Item> ICE_SHIELD = REGISTRY.register("ice_shield", () -> new IceShieldItem());
	public static final RegistryObject<Item> SNOW_GOLEM_CREATOR = REGISTRY.register("snow_golem_creator", () -> new SnowGolemCreatorItem());
	public static final RegistryObject<Item> ICE_SHARP = REGISTRY.register("ice_sharp", () -> new IceSharpItem());
	public static final RegistryObject<Item> PLASMA_BALL = REGISTRY.register("plasma_ball", () -> new PlasmaBallItem());
	public static final RegistryObject<Item> STORM = REGISTRY.register("storm", () -> new StormItem());
	public static final RegistryObject<Item> SOUND_SWORD = REGISTRY.register("sound_sword", () -> new SoundSwordItem());
	public static final RegistryObject<Item> ACUSTICAL_EXPLODE = REGISTRY.register("acustical_explode", () -> new AcusticalExplodeItem());
	public static final RegistryObject<Item> SOUND_BARRIER_BLOCK = block(PowerModBlocks.SOUND_BARRIER_BLOCK, null);
	public static final RegistryObject<Item> SOUND_BARRIER = REGISTRY.register("sound_barrier", () -> new SoundBarrierItem());
	public static final RegistryObject<Item> SOUND_EMITATE = REGISTRY.register("sound_emitate", () -> new SoundEmitateItem());
	public static final RegistryObject<Item> CLUSTER_SHARP = REGISTRY.register("cluster_sharp", () -> new ClusterSharpItem());
	public static final RegistryObject<Item> CLUSTER_BLOCK = block(PowerModBlocks.CLUSTER_BLOCK, null);
	public static final RegistryObject<Item> CRYSTAL_SHIELD_BLOCK = block(PowerModBlocks.CRYSTAL_SHIELD_BLOCK, null);
	public static final RegistryObject<Item> CRYSTAL_SHIELD = REGISTRY.register("crystal_shield", () -> new CrystalShieldItem());
	public static final RegistryObject<Item> LAVA_HOLE = REGISTRY.register("lava_hole", () -> new LavaHoleItem());
	public static final RegistryObject<Item> LAVA_BALL = REGISTRY.register("lava_ball", () -> new LavaBallItem());
	public static final RegistryObject<Item> RAINFALL = REGISTRY.register("rainfall", () -> new RainfallItem());
	public static final RegistryObject<Item> RAIN_KNIFE = REGISTRY.register("rain_knife", () -> new RainKnifeItem());
	public static final RegistryObject<Item> TORNADO_CREATE = REGISTRY.register("tornado_create", () -> new TornadoCreateItem());
	public static final RegistryObject<Item> CORAL_SHIELD = REGISTRY.register("coral_shield", () -> new CoralShieldItem());
	public static final RegistryObject<Item> WHIRLPOOL = REGISTRY.register("whirlpool", () -> new WhirlpoolItem());
	public static final RegistryObject<Item> OCEAN_SWORD = REGISTRY.register("ocean_sword", () -> new OceanSwordItem());
	public static final RegistryObject<Item> ICE_HELMET = REGISTRY.register("ice_helmet", () -> new IceItem.Helmet());
	public static final RegistryObject<Item> ICE_CHESTPLATE = REGISTRY.register("ice_chestplate", () -> new IceItem.Chestplate());
	public static final RegistryObject<Item> ICE_LEGGINGS = REGISTRY.register("ice_leggings", () -> new IceItem.Leggings());
	public static final RegistryObject<Item> ICE_BOOTS = REGISTRY.register("ice_boots", () -> new IceItem.Boots());
	public static final RegistryObject<Item> LIGHTNING_HELMET = REGISTRY.register("lightning_helmet", () -> new LightningItem.Helmet());
	public static final RegistryObject<Item> LIGHTNING_CHESTPLATE = REGISTRY.register("lightning_chestplate", () -> new LightningItem.Chestplate());
	public static final RegistryObject<Item> LIGHTNING_LEGGINGS = REGISTRY.register("lightning_leggings", () -> new LightningItem.Leggings());
	public static final RegistryObject<Item> LIGHTNING_BOOTS = REGISTRY.register("lightning_boots", () -> new LightningItem.Boots());
	public static final RegistryObject<Item> SOUND_HELMET = REGISTRY.register("sound_helmet", () -> new SoundItem.Helmet());
	public static final RegistryObject<Item> SOUND_CHESTPLATE = REGISTRY.register("sound_chestplate", () -> new SoundItem.Chestplate());
	public static final RegistryObject<Item> SOUND_LEGGINGS = REGISTRY.register("sound_leggings", () -> new SoundItem.Leggings());
	public static final RegistryObject<Item> SOUND_BOOTS = REGISTRY.register("sound_boots", () -> new SoundItem.Boots());
	public static final RegistryObject<Item> CRYSTAL_HELMET = REGISTRY.register("crystal_helmet", () -> new CrystalItem.Helmet());
	public static final RegistryObject<Item> CRYSTAL_CHESTPLATE = REGISTRY.register("crystal_chestplate", () -> new CrystalItem.Chestplate());
	public static final RegistryObject<Item> CRYSTAL_LEGGINGS = REGISTRY.register("crystal_leggings", () -> new CrystalItem.Leggings());
	public static final RegistryObject<Item> CRYSTAL_BOOTS = REGISTRY.register("crystal_boots", () -> new CrystalItem.Boots());
	public static final RegistryObject<Item> LAVA_HELMET = REGISTRY.register("lava_helmet", () -> new LavaItem.Helmet());
	public static final RegistryObject<Item> LAVA_CHESTPLATE = REGISTRY.register("lava_chestplate", () -> new LavaItem.Chestplate());
	public static final RegistryObject<Item> LAVA_LEGGINGS = REGISTRY.register("lava_leggings", () -> new LavaItem.Leggings());
	public static final RegistryObject<Item> LAVA_BOOTS = REGISTRY.register("lava_boots", () -> new LavaItem.Boots());
	public static final RegistryObject<Item> RAIN_HELMET = REGISTRY.register("rain_helmet", () -> new RainItem.Helmet());
	public static final RegistryObject<Item> RAIN_CHESTPLATE = REGISTRY.register("rain_chestplate", () -> new RainItem.Chestplate());
	public static final RegistryObject<Item> RAIN_LEGGINGS = REGISTRY.register("rain_leggings", () -> new RainItem.Leggings());
	public static final RegistryObject<Item> RAIN_BOOTS = REGISTRY.register("rain_boots", () -> new RainItem.Boots());
	public static final RegistryObject<Item> TORNADO_HELMET = REGISTRY.register("tornado_helmet", () -> new TornadoItem.Helmet());
	public static final RegistryObject<Item> TORNADO_CHESTPLATE = REGISTRY.register("tornado_chestplate", () -> new TornadoItem.Chestplate());
	public static final RegistryObject<Item> TORNADO_LEGGINGS = REGISTRY.register("tornado_leggings", () -> new TornadoItem.Leggings());
	public static final RegistryObject<Item> TORNADO_BOOTS = REGISTRY.register("tornado_boots", () -> new TornadoItem.Boots());
	public static final RegistryObject<Item> OCEAN_HELMET = REGISTRY.register("ocean_helmet", () -> new OceanItem.Helmet());
	public static final RegistryObject<Item> OCEAN_CHESTPLATE = REGISTRY.register("ocean_chestplate", () -> new OceanItem.Chestplate());
	public static final RegistryObject<Item> OCEAN_LEGGINGS = REGISTRY.register("ocean_leggings", () -> new OceanItem.Leggings());
	public static final RegistryObject<Item> OCEAN_BOOTS = REGISTRY.register("ocean_boots", () -> new OceanItem.Boots());
	public static final RegistryObject<Item> LIGHTNING_STRIKE = REGISTRY.register("lightning_strike", () -> new LightningStrikeItem());
	public static final RegistryObject<Item> ENERGY_STAFF = REGISTRY.register("energy_staff", () -> new EnergyStaffItem());
	public static final RegistryObject<Item> FIRE_SWORD = REGISTRY.register("fire_sword", () -> new FireSwordItem());
	public static final RegistryObject<Item> AIR_BLADE = REGISTRY.register("air_blade", () -> new AirBladeItem());
	public static final RegistryObject<Item> WATER_KATANA = REGISTRY.register("water_katana", () -> new WaterKatanaItem());
	public static final RegistryObject<Item> CRYSTAL_DAGGER = REGISTRY.register("crystal_dagger", () -> new CrystalDaggerItem());
	public static final RegistryObject<Item> LAVA_HAMMER = REGISTRY.register("lava_hammer", () -> new LavaHammerItem());
	public static final RegistryObject<Item> RAIN_BOW = REGISTRY.register("rain_bow", () -> new RainBowItem());
	public static final RegistryObject<Item> TORNADO_BATTLE_AXE = REGISTRY.register("tornado_battle_axe", () -> new TornadoBattleAxeItem());
	public static final RegistryObject<Item> MAGMA_SHIELD = REGISTRY.register("magma_shield", () -> new MagmaShieldItem());
	public static final RegistryObject<Item> ROSE_SWORD = REGISTRY.register("rose_sword", () -> new RoseSwordItem());
	public static final RegistryObject<Item> WOODEN_SHIELD = REGISTRY.register("wooden_shield", () -> new WoodenShieldItem());
	public static final RegistryObject<Item> SPIKE = REGISTRY.register("spike", () -> new SpikeItem());
	public static final RegistryObject<Item> FERTILIZER = REGISTRY.register("fertilizer", () -> new FertilizerItem());
	public static final RegistryObject<Item> CULTIVATION = REGISTRY.register("cultivation", () -> new CultivationItem());
	public static final RegistryObject<Item> BEE_STING = REGISTRY.register("bee_sting", () -> new BeeStingItem());
	public static final RegistryObject<Item> TIGER_CLAW = REGISTRY.register("tiger_claw", () -> new TigerClawItem());
	public static final RegistryObject<Item> TAMER = REGISTRY.register("tamer", () -> new TamerItem());
	public static final RegistryObject<Item> SPAWN = REGISTRY.register("spawn", () -> new SpawnItem());
	public static final RegistryObject<Item> SHURIKEN = REGISTRY.register("shuriken", () -> new ShurikenItem());
	public static final RegistryObject<Item> SAI = REGISTRY.register("sai", () -> new SaiItem());
	public static final RegistryObject<Item> METAL_INVULNERABILITY = REGISTRY.register("metal_invulnerability", () -> new MetalInvulnerabilityItem());
	public static final RegistryObject<Item> IRON_GOLEM_CREATE = REGISTRY.register("iron_golem_create", () -> new IronGolemCreateItem());
	public static final RegistryObject<Item> IRON_SHIELD = REGISTRY.register("iron_shield", () -> new IronShieldItem());
	public static final RegistryObject<Item> LIGHT_SWORD = REGISTRY.register("light_sword", () -> new LightSwordItem());
	public static final RegistryObject<Item> FLASH_LIGHT = REGISTRY.register("flash_light", () -> new FlashLightItem());
	public static final RegistryObject<Item> GLOW_CREATE = REGISTRY.register("glow_create", () -> new GlowCreateItem());
	public static final RegistryObject<Item> LIGHTING = REGISTRY.register("lighting", () -> new LightingItem());
	public static final RegistryObject<Item> SHADOW_SWORD = REGISTRY.register("shadow_sword", () -> new ShadowSwordItem());
	public static final RegistryObject<Item> SHADOW_BALL = REGISTRY.register("shadow_ball", () -> new ShadowBallItem());
	public static final RegistryObject<Item> SHADOW_INVISIBLE = REGISTRY.register("shadow_invisible", () -> new ShadowInvisibleItem());
	public static final RegistryObject<Item> CREATE_SHADOW = REGISTRY.register("create_shadow", () -> new CreateShadowItem());
	public static final RegistryObject<Item> VACUUM_SWORD = REGISTRY.register("vacuum_sword", () -> new VacuumSwordItem());
	public static final RegistryObject<Item> VACUUM_SPIRAL = REGISTRY.register("vacuum_spiral", () -> new VacuumSpiralItem());
	public static final RegistryObject<Item> VACUUM_WEB_BLOCK = block(PowerModBlocks.VACUUM_WEB_BLOCK, null);
	public static final RegistryObject<Item> VACUUM_WEB = REGISTRY.register("vacuum_web", () -> new VacuumWebItem());
	public static final RegistryObject<Item> SUN_AXE = REGISTRY.register("sun_axe", () -> new SunAxeItem());
	public static final RegistryObject<Item> SUN_EXPLODE = REGISTRY.register("sun_explode", () -> new SunExplodeItem());
	public static final RegistryObject<Item> SUN_RAY = REGISTRY.register("sun_ray", () -> new SunRayItem());
	public static final RegistryObject<Item> SUN_REGENERATION = REGISTRY.register("sun_regeneration", () -> new SunRegenerationItem());
	public static final RegistryObject<Item> MOON_AXE = REGISTRY.register("moon_axe", () -> new MoonAxeItem());
	public static final RegistryObject<Item> MOON_STONES = REGISTRY.register("moon_stones", () -> new MoonStonesItem());
	public static final RegistryObject<Item> MOON_STONES_BLOCK = block(PowerModBlocks.MOON_STONES_BLOCK, null);
	public static final RegistryObject<Item> ECLIPSE = REGISTRY.register("eclipse", () -> new EclipseItem());
	public static final RegistryObject<Item> MOON_WITHER = REGISTRY.register("moon_wither", () -> new MoonWitherItem());
	public static final RegistryObject<Item> RANDOM_ITEM = REGISTRY.register("random_item", () -> new RandomItemItem());
	public static final RegistryObject<Item> DESTRUCTION_POWER = REGISTRY.register("destruction_power", () -> new DestructionPowerItem());
	public static final RegistryObject<Item> TP_ON_MARS = REGISTRY.register("tp_on_mars", () -> new TpOnMarsItem());
	public static final RegistryObject<Item> TP_ON_VENUS = REGISTRY.register("tp_on_venus", () -> new TpOnVenusItem());
	public static final RegistryObject<Item> TP_ON_MOON = REGISTRY.register("tp_on_moon", () -> new TpOnMoonItem());
	public static final RegistryObject<Item> TP_ON_EARTH = REGISTRY.register("tp_on_earth", () -> new TpOnEarthItem());
	public static final RegistryObject<Item> GALACTIC_SWORD = REGISTRY.register("galactic_sword", () -> new GalacticSwordItem());
	public static final RegistryObject<Item> BLACK_HOLE = REGISTRY.register("black_hole", () -> new BlackHoleItem());
	public static final RegistryObject<Item> BLACK_HOLE_BLOCK = block(PowerModBlocks.BLACK_HOLE_BLOCK, null);
	public static final RegistryObject<Item> GREENERY_HELMET = REGISTRY.register("greenery_helmet", () -> new GreeneryItem.Helmet());
	public static final RegistryObject<Item> GREENERY_CHESTPLATE = REGISTRY.register("greenery_chestplate", () -> new GreeneryItem.Chestplate());
	public static final RegistryObject<Item> GREENERY_LEGGINGS = REGISTRY.register("greenery_leggings", () -> new GreeneryItem.Leggings());
	public static final RegistryObject<Item> GREENERY_BOOTS = REGISTRY.register("greenery_boots", () -> new GreeneryItem.Boots());
	public static final RegistryObject<Item> UNMULTIPLICATION_MOON_STONES_BLOCK = block(PowerModBlocks.UNMULTIPLICATION_MOON_STONES_BLOCK, null);
	public static final RegistryObject<Item> ANIMALS_HELMET = REGISTRY.register("animals_helmet", () -> new AnimalsItem.Helmet());
	public static final RegistryObject<Item> ANIMALS_CHESTPLATE = REGISTRY.register("animals_chestplate", () -> new AnimalsItem.Chestplate());
	public static final RegistryObject<Item> ANIMALS_LEGGINGS = REGISTRY.register("animals_leggings", () -> new AnimalsItem.Leggings());
	public static final RegistryObject<Item> ANIMALS_BOOTS = REGISTRY.register("animals_boots", () -> new AnimalsItem.Boots());
	public static final RegistryObject<Item> METAL_HELMET = REGISTRY.register("metal_helmet", () -> new MetalItem.Helmet());
	public static final RegistryObject<Item> METAL_CHESTPLATE = REGISTRY.register("metal_chestplate", () -> new MetalItem.Chestplate());
	public static final RegistryObject<Item> METAL_LEGGINGS = REGISTRY.register("metal_leggings", () -> new MetalItem.Leggings());
	public static final RegistryObject<Item> METAL_BOOTS = REGISTRY.register("metal_boots", () -> new MetalItem.Boots());
	public static final RegistryObject<Item> LIGHT_HELMET = REGISTRY.register("light_helmet", () -> new LightItem.Helmet());
	public static final RegistryObject<Item> LIGHT_CHESTPLATE = REGISTRY.register("light_chestplate", () -> new LightItem.Chestplate());
	public static final RegistryObject<Item> LIGHT_LEGGINGS = REGISTRY.register("light_leggings", () -> new LightItem.Leggings());
	public static final RegistryObject<Item> LIGHT_BOOTS = REGISTRY.register("light_boots", () -> new LightItem.Boots());
	public static final RegistryObject<Item> SHADOW_HELMET = REGISTRY.register("shadow_helmet", () -> new ShadowarmorItem.Helmet());
	public static final RegistryObject<Item> SHADOW_CHESTPLATE = REGISTRY.register("shadow_chestplate", () -> new ShadowarmorItem.Chestplate());
	public static final RegistryObject<Item> SHADOW_LEGGINGS = REGISTRY.register("shadow_leggings", () -> new ShadowarmorItem.Leggings());
	public static final RegistryObject<Item> SHADOW_BOOTS = REGISTRY.register("shadow_boots", () -> new ShadowarmorItem.Boots());
	public static final RegistryObject<Item> CRESTCENT_HELMET = REGISTRY.register("crestcent_helmet", () -> new CrestcentItem.Helmet());
	public static final RegistryObject<Item> CRESTCENT_CHESTPLATE = REGISTRY.register("crestcent_chestplate", () -> new CrestcentItem.Chestplate());
	public static final RegistryObject<Item> CRESTCENT_LEGGINGS = REGISTRY.register("crestcent_leggings", () -> new CrestcentItem.Leggings());
	public static final RegistryObject<Item> CRESTCENT_BOOTS = REGISTRY.register("crestcent_boots", () -> new CrestcentItem.Boots());
	public static final RegistryObject<Item> SUN_HELMET = REGISTRY.register("sun_helmet", () -> new SunItem.Helmet());
	public static final RegistryObject<Item> SUN_CHESTPLATE = REGISTRY.register("sun_chestplate", () -> new SunItem.Chestplate());
	public static final RegistryObject<Item> SUN_LEGGINGS = REGISTRY.register("sun_leggings", () -> new SunItem.Leggings());
	public static final RegistryObject<Item> SUN_BOOTS = REGISTRY.register("sun_boots", () -> new SunItem.Boots());
	public static final RegistryObject<Item> VACUUM_HELMET = REGISTRY.register("vacuum_helmet", () -> new VacuumItem.Helmet());
	public static final RegistryObject<Item> VACUUM_CHESTPLATE = REGISTRY.register("vacuum_chestplate", () -> new VacuumItem.Chestplate());
	public static final RegistryObject<Item> VACUUM_LEGGINGS = REGISTRY.register("vacuum_leggings", () -> new VacuumItem.Leggings());
	public static final RegistryObject<Item> VACUUM_BOOTS = REGISTRY.register("vacuum_boots", () -> new VacuumItem.Boots());
	public static final RegistryObject<Item> CREATION_HELMET = REGISTRY.register("creation_helmet", () -> new CreationItem.Helmet());
	public static final RegistryObject<Item> CREATION_CHESTPLATE = REGISTRY.register("creation_chestplate", () -> new CreationItem.Chestplate());
	public static final RegistryObject<Item> CREATION_LEGGINGS = REGISTRY.register("creation_leggings", () -> new CreationItem.Leggings());
	public static final RegistryObject<Item> CREATION_BOOTS = REGISTRY.register("creation_boots", () -> new CreationItem.Boots());
	public static final RegistryObject<Item> DESTRUCTION_HELMET = REGISTRY.register("destruction_helmet", () -> new DestructionItem.Helmet());
	public static final RegistryObject<Item> DESTRUCTION_CHESTPLATE = REGISTRY.register("destruction_chestplate",
			() -> new DestructionItem.Chestplate());
	public static final RegistryObject<Item> DESTRUCTION_LEGGINGS = REGISTRY.register("destruction_leggings", () -> new DestructionItem.Leggings());
	public static final RegistryObject<Item> DESTRUCTION_BOOTS = REGISTRY.register("destruction_boots", () -> new DestructionItem.Boots());
	public static final RegistryObject<Item> COSMOS_HELMET = REGISTRY.register("cosmos_helmet", () -> new CosmosItem.Helmet());
	public static final RegistryObject<Item> COSMOS_CHESTPLATE = REGISTRY.register("cosmos_chestplate", () -> new CosmosItem.Chestplate());
	public static final RegistryObject<Item> COSMOS_LEGGINGS = REGISTRY.register("cosmos_leggings", () -> new CosmosItem.Leggings());
	public static final RegistryObject<Item> COSMOS_BOOTS = REGISTRY.register("cosmos_boots", () -> new CosmosItem.Boots());
	public static final RegistryObject<Item> BLOOD_HELMET = REGISTRY.register("blood_helmet", () -> new BloodItem.Helmet());
	public static final RegistryObject<Item> BLOOD_CHESTPLATE = REGISTRY.register("blood_chestplate", () -> new BloodItem.Chestplate());
	public static final RegistryObject<Item> BLOOD_LEGGINGS = REGISTRY.register("blood_leggings", () -> new BloodItem.Leggings());
	public static final RegistryObject<Item> BLOOD_BOOTS = REGISTRY.register("blood_boots", () -> new BloodItem.Boots());
	public static final RegistryObject<Item> VAMPIRISM = REGISTRY.register("vampirism", () -> new VampirismItem());
	public static final RegistryObject<Item> BLOOD_REAPER = REGISTRY.register("blood_reaper", () -> new BloodReaperItem());
	public static final RegistryObject<Item> BLACK_HEART = REGISTRY.register("black_heart", () -> new BlackHeartItem());
	public static final RegistryObject<Item> TIME_HELMET = REGISTRY.register("time_helmet", () -> new TimeItem.Helmet());
	public static final RegistryObject<Item> TIME_CHESTPLATE = REGISTRY.register("time_chestplate", () -> new TimeItem.Chestplate());
	public static final RegistryObject<Item> TIME_LEGGINGS = REGISTRY.register("time_leggings", () -> new TimeItem.Leggings());
	public static final RegistryObject<Item> TIME_BOOTS = REGISTRY.register("time_boots", () -> new TimeItem.Boots());
	public static final RegistryObject<Item> TIME_BLADE = REGISTRY.register("time_blade", () -> new TimeBladeItem());
	public static final RegistryObject<Item> ACCELERATION_TIME = REGISTRY.register("acceleration_time", () -> new AccelerationTimeItem());
	public static final RegistryObject<Item> TIME_STOP = REGISTRY.register("time_stop", () -> new TimeStopItem());
	public static final RegistryObject<Item> TIME_REVERSED = REGISTRY.register("time_reversed", () -> new TimeReversedItem());
	public static final RegistryObject<Item> TIME_DILATION = REGISTRY.register("time_dilation", () -> new TimeDilationItem());
	public static final RegistryObject<Item> TECHNOLOGY_HELMET = REGISTRY.register("technology_helmet", () -> new TechnologyItem.Helmet());
	public static final RegistryObject<Item> TECHNOLOGY_CHESTPLATE = REGISTRY.register("technology_chestplate",
			() -> new TechnologyItem.Chestplate());
	public static final RegistryObject<Item> TECHNOLOGY_LEGGINGS = REGISTRY.register("technology_leggings", () -> new TechnologyItem.Leggings());
	public static final RegistryObject<Item> TECHNOLOGY_BOOTS = REGISTRY.register("technology_boots", () -> new TechnologyItem.Boots());
	public static final RegistryObject<Item> TECHNO_PICKAXE = REGISTRY.register("techno_pickaxe", () -> new TechnoPickaxeItem());
	public static final RegistryObject<Item> TECHNOBARRIER_BLOCK = block(PowerModBlocks.TECHNOBARRIER_BLOCK, null);
	public static final RegistryObject<Item> TECHNOBARRIER = REGISTRY.register("technobarrier", () -> new TechnobarrierItem());
	public static final RegistryObject<Item> MEGAWATT = REGISTRY.register("megawatt", () -> new MegawattItem());
	public static final RegistryObject<Item> REDSTONE_BUNDLE = REGISTRY.register("redstone_bundle", () -> new RedstoneBundleItem());
	public static final RegistryObject<Item> TELEPORTATION_HELMET = REGISTRY.register("teleportation_helmet", () -> new TeleportationItem.Helmet());
	public static final RegistryObject<Item> TELEPORTATION_CHESTPLATE = REGISTRY.register("teleportation_chestplate",
			() -> new TeleportationItem.Chestplate());
	public static final RegistryObject<Item> TELEPORTATION_LEGGINGS = REGISTRY.register("teleportation_leggings",
			() -> new TeleportationItem.Leggings());
	public static final RegistryObject<Item> TELEPORTATION_BOOTS = REGISTRY.register("teleportation_boots", () -> new TeleportationItem.Boots());
	public static final RegistryObject<Item> BLUE_KNIFE = REGISTRY.register("blue_knife", () -> new BlueKnifeItem());
	public static final RegistryObject<Item> CHECKPOINT = REGISTRY.register("checkpoint", () -> new CheckpointItem());
	public static final RegistryObject<Item> PORTAL_BLAST = REGISTRY.register("portal_blast", () -> new PortalBlastItem());
	public static final RegistryObject<Item> BLUE_PORTAL = block(PowerModBlocks.BLUE_PORTAL, null);
	public static final RegistryObject<Item> ORANGE_PORTAL = block(PowerModBlocks.ORANGE_PORTAL, null);
	public static final RegistryObject<Item> EXPLODE_HELMET = REGISTRY.register("explode_helmet", () -> new ExplodeItem.Helmet());
	public static final RegistryObject<Item> EXPLODE_CHESTPLATE = REGISTRY.register("explode_chestplate", () -> new ExplodeItem.Chestplate());
	public static final RegistryObject<Item> EXPLODE_LEGGINGS = REGISTRY.register("explode_leggings", () -> new ExplodeItem.Leggings());
	public static final RegistryObject<Item> EXPLODE_BOOTS = REGISTRY.register("explode_boots", () -> new ExplodeItem.Boots());
	public static final RegistryObject<Item> DETONATOR_TNT = block(PowerModBlocks.DETONATOR_TNT, null);
	public static final RegistryObject<Item> EXPLOSIVE_FLOW = REGISTRY.register("explosive_flow", () -> new ExplosiveFlowItem());
	public static final RegistryObject<Item> ICE_SPEAR = REGISTRY.register("ice_spear", () -> new IceSpearItem());
	public static final RegistryObject<Item> GOLDEN_CROSSBOW = REGISTRY.register("golden_crossbow", () -> new GoldenCrossbowItem());
	public static final RegistryObject<Item> DESTRUCTION_SPHERE = REGISTRY.register("destruction_sphere", () -> new DestructionSphereItem());
	public static final RegistryObject<Item> AMBER_HELMET = REGISTRY.register("amber_helmet", () -> new AmberItem.Helmet());
	public static final RegistryObject<Item> AMBER_CHESTPLATE = REGISTRY.register("amber_chestplate", () -> new AmberItem.Chestplate());
	public static final RegistryObject<Item> AMBER_LEGGINGS = REGISTRY.register("amber_leggings", () -> new AmberItem.Leggings());
	public static final RegistryObject<Item> AMBER_BOOTS = REGISTRY.register("amber_boots", () -> new AmberItem.Boots());
	public static final RegistryObject<Item> CONSTRUCTIONS = REGISTRY.register("constructions", () -> new ConstructionsItem());
	public static final RegistryObject<Item> BO_STAFF = REGISTRY.register("bo_staff", () -> new BoStaffItem());
	public static final RegistryObject<Item> INCREASE_POWER = REGISTRY.register("increase_power", () -> new IncreasePowerItem());
	public static final RegistryObject<Item> ENERGY_ABSORPTION = REGISTRY.register("energy_absorption", () -> new EnergyAbsorptionItem());
	public static final RegistryObject<Item> BOOK_OF_ELEMENTS = REGISTRY.register("book_of_elements", () -> new BookOfElementsItem());
	public static final RegistryObject<Item> MUSHROOMS_STONE = REGISTRY.register("mushrooms_stone", () -> new MushroomsStoneItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
